language: android

env:
  global:
    - NDK_VERSION=r18b #r19c
    #https://github.com/android-ndk/ndk/wiki/Changelog-r19

android:
  components:
    # We call "tools" twice to get the latest Android SDK tools.
    - tools
    - platform-tools
    - tools

    # The SDK version used to compile this program. This is NOT the minimum requirement.
    - android-27

    # We need a specific version of BuildTools to get this working.
    - build-tools-28.0.3

licenses:
  - 'android-sdk-license-.+'
  - 'android-sdk-preview-license-.+'
  - '.+'

before_install:
  - wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip
  - unzip -q android-ndk-${NDK_VERSION}-linux-x86_64.zip -d /usr/local/android-sdk
  - mv /usr/local/android-sdk/android-ndk-${NDK_VERSION} /usr/local/android-sdk/ndk-bundle

